# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.3.4
_src_path: git+https://github.com/OCA/oca-addons-repo-template
ci: Travis
dependency_installation_mode: PIP
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 13.0
rebel_module_groups: []
repo_description: These modules complement the official l10n_be.
repo_name: Odoo modules for Belgium
repo_slug: l10n-belgium
travis_apt_packages: []
travis_apt_sources: []
